# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  iimnetwork:

services:
  couchdbPeer0IIM:
    container_name: couchdbPeer0IIM
    image: couchdb:3.1.1
    
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw

    ports:
      - "5984:5984"
    networks:
      - iimnetwork

  peer0.iimudaipur.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdbPeer0IIM:5984

      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    depends_on:
      - couchdbPeer0IIM

  couchdbPeer1IIM:
    container_name: couchdbPeer1IIM
    image: couchdb:3.1.1
    
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw

    ports:
      - "6984:5984"
    networks:
      - iimnetwork

  peer1.iimudaipur.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdbPeer1IIM:5984

      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    depends_on:
      - couchdbPeer1IIM
